//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.dbconection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priem
    {
        public int Id { get; set; }
        public Nullable<int> Idanimal { get; set; }
        public Nullable<int> Iddoctor { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Coment { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
